// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestMessage_Type int32

const (
	RequestMessage_PUT_TASK       RequestMessage_Type = 0
	RequestMessage_INIT           RequestMessage_Type = 1
	RequestMessage_SET_STATISTIC  RequestMessage_Type = 2
	RequestMessage_SET_ERROR_RATE RequestMessage_Type = 3
)

var RequestMessage_Type_name = map[int32]string{
	0: "PUT_TASK",
	1: "INIT",
	2: "SET_STATISTIC",
	3: "SET_ERROR_RATE",
}

var RequestMessage_Type_value = map[string]int32{
	"PUT_TASK":       0,
	"INIT":           1,
	"SET_STATISTIC":  2,
	"SET_ERROR_RATE": 3,
}

func (x RequestMessage_Type) String() string {
	return proto.EnumName(RequestMessage_Type_name, int32(x))
}

func (RequestMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4, 0}
}

type ServiceMessage_Type int32

const (
	ServiceMessage_GET_TASK      ServiceMessage_Type = 0
	ServiceMessage_INIT_RESPONSE ServiceMessage_Type = 1
)

var ServiceMessage_Type_name = map[int32]string{
	0: "GET_TASK",
	1: "INIT_RESPONSE",
}

var ServiceMessage_Type_value = map[string]int32{
	"GET_TASK":      0,
	"INIT_RESPONSE": 1,
}

func (x ServiceMessage_Type) String() string {
	return proto.EnumName(ServiceMessage_Type_name, int32(x))
}

func (ServiceMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7, 0}
}

type PutTask struct {
	CustomData           []byte   `protobuf:"bytes,1,opt,name=customData,proto3" json:"customData,omitempty"`
	TaskUUID             string   `protobuf:"bytes,2,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutTask) Reset()         { *m = PutTask{} }
func (m *PutTask) String() string { return proto.CompactTextString(m) }
func (*PutTask) ProtoMessage()    {}
func (*PutTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *PutTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutTask.Unmarshal(m, b)
}
func (m *PutTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutTask.Marshal(b, m, deterministic)
}
func (m *PutTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutTask.Merge(m, src)
}
func (m *PutTask) XXX_Size() int {
	return xxx_messageInfo_PutTask.Size(m)
}
func (m *PutTask) XXX_DiscardUnknown() {
	xxx_messageInfo_PutTask.DiscardUnknown(m)
}

var xxx_messageInfo_PutTask proto.InternalMessageInfo

func (m *PutTask) GetCustomData() []byte {
	if m != nil {
		return m.CustomData
	}
	return nil
}

func (m *PutTask) GetTaskUUID() string {
	if m != nil {
		return m.TaskUUID
	}
	return ""
}

type Init struct {
	InitStat             *Statistic `protobuf:"bytes,1,opt,name=init_stat,json=initStat,proto3" json:"init_stat,omitempty"`
	AccountId            int32      `protobuf:"zigzag32,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ApiKey               string     `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RuleId               int32      `protobuf:"zigzag32,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	ReferenceIp          string     `protobuf:"bytes,5,opt,name=reference_ip,json=referenceIp,proto3" json:"reference_ip,omitempty"`
	QueueId              int32      `protobuf:"zigzag32,6,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	SessionId            string     `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MaximumErrorRate     float64    `protobuf:"fixed64,12,opt,name=maximum_error_rate,json=maximumErrorRate,proto3" json:"maximum_error_rate,omitempty"`
	Version              int32      `protobuf:"zigzag32,13,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Init) Reset()         { *m = Init{} }
func (m *Init) String() string { return proto.CompactTextString(m) }
func (*Init) ProtoMessage()    {}
func (*Init) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Init) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Init.Unmarshal(m, b)
}
func (m *Init) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Init.Marshal(b, m, deterministic)
}
func (m *Init) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Init.Merge(m, src)
}
func (m *Init) XXX_Size() int {
	return xxx_messageInfo_Init.Size(m)
}
func (m *Init) XXX_DiscardUnknown() {
	xxx_messageInfo_Init.DiscardUnknown(m)
}

var xxx_messageInfo_Init proto.InternalMessageInfo

func (m *Init) GetInitStat() *Statistic {
	if m != nil {
		return m.InitStat
	}
	return nil
}

func (m *Init) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Init) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *Init) GetRuleId() int32 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *Init) GetReferenceIp() string {
	if m != nil {
		return m.ReferenceIp
	}
	return ""
}

func (m *Init) GetQueueId() int32 {
	if m != nil {
		return m.QueueId
	}
	return 0
}

func (m *Init) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Init) GetMaximumErrorRate() float64 {
	if m != nil {
		return m.MaximumErrorRate
	}
	return 0
}

func (m *Init) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Statistic struct {
	AvgTimeTalkSec       float64  `protobuf:"fixed64,1,opt,name=avgTimeTalkSec,proto3" json:"avgTimeTalkSec,omitempty"`
	PercentSuccessful    float64  `protobuf:"fixed64,2,opt,name=percentSuccessful,proto3" json:"percentSuccessful,omitempty"`
	AvgDialTimeSec       float64  `protobuf:"fixed64,3,opt,name=avgDialTimeSec,proto3" json:"avgDialTimeSec,omitempty"`
	AvgTotalTimeSec      float64  `protobuf:"fixed64,4,opt,name=avgTotalTimeSec,proto3" json:"avgTotalTimeSec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statistic) Reset()         { *m = Statistic{} }
func (m *Statistic) String() string { return proto.CompactTextString(m) }
func (*Statistic) ProtoMessage()    {}
func (*Statistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Statistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistic.Unmarshal(m, b)
}
func (m *Statistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistic.Marshal(b, m, deterministic)
}
func (m *Statistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistic.Merge(m, src)
}
func (m *Statistic) XXX_Size() int {
	return xxx_messageInfo_Statistic.Size(m)
}
func (m *Statistic) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistic.DiscardUnknown(m)
}

var xxx_messageInfo_Statistic proto.InternalMessageInfo

func (m *Statistic) GetAvgTimeTalkSec() float64 {
	if m != nil {
		return m.AvgTimeTalkSec
	}
	return 0
}

func (m *Statistic) GetPercentSuccessful() float64 {
	if m != nil {
		return m.PercentSuccessful
	}
	return 0
}

func (m *Statistic) GetAvgDialTimeSec() float64 {
	if m != nil {
		return m.AvgDialTimeSec
	}
	return 0
}

func (m *Statistic) GetAvgTotalTimeSec() float64 {
	if m != nil {
		return m.AvgTotalTimeSec
	}
	return 0
}

type ErrRate struct {
	MaximumErrorRate     float64  `protobuf:"fixed64,1,opt,name=maximum_error_rate,json=maximumErrorRate,proto3" json:"maximum_error_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrRate) Reset()         { *m = ErrRate{} }
func (m *ErrRate) String() string { return proto.CompactTextString(m) }
func (*ErrRate) ProtoMessage()    {}
func (*ErrRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ErrRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrRate.Unmarshal(m, b)
}
func (m *ErrRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrRate.Marshal(b, m, deterministic)
}
func (m *ErrRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrRate.Merge(m, src)
}
func (m *ErrRate) XXX_Size() int {
	return xxx_messageInfo_ErrRate.Size(m)
}
func (m *ErrRate) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrRate.DiscardUnknown(m)
}

var xxx_messageInfo_ErrRate proto.InternalMessageInfo

func (m *ErrRate) GetMaximumErrorRate() float64 {
	if m != nil {
		return m.MaximumErrorRate
	}
	return 0
}

type RequestMessage struct {
	Type                 RequestMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=RequestMessage_Type" json:"type,omitempty"`
	Task                 *PutTask            `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Init                 *Init               `protobuf:"bytes,3,opt,name=init,proto3" json:"init,omitempty"`
	Statistic            *Statistic          `protobuf:"bytes,4,opt,name=statistic,proto3" json:"statistic,omitempty"`
	ErrRate              *ErrRate            `protobuf:"bytes,5,opt,name=errRate,proto3" json:"errRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RequestMessage) Reset()         { *m = RequestMessage{} }
func (m *RequestMessage) String() string { return proto.CompactTextString(m) }
func (*RequestMessage) ProtoMessage()    {}
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *RequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMessage.Unmarshal(m, b)
}
func (m *RequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMessage.Marshal(b, m, deterministic)
}
func (m *RequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMessage.Merge(m, src)
}
func (m *RequestMessage) XXX_Size() int {
	return xxx_messageInfo_RequestMessage.Size(m)
}
func (m *RequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMessage proto.InternalMessageInfo

func (m *RequestMessage) GetType() RequestMessage_Type {
	if m != nil {
		return m.Type
	}
	return RequestMessage_PUT_TASK
}

func (m *RequestMessage) GetTask() *PutTask {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *RequestMessage) GetInit() *Init {
	if m != nil {
		return m.Init
	}
	return nil
}

func (m *RequestMessage) GetStatistic() *Statistic {
	if m != nil {
		return m.Statistic
	}
	return nil
}

func (m *RequestMessage) GetErrRate() *ErrRate {
	if m != nil {
		return m.ErrRate
	}
	return nil
}

type GetTask struct {
	Count                int32    `protobuf:"zigzag32,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTask) Reset()         { *m = GetTask{} }
func (m *GetTask) String() string { return proto.CompactTextString(m) }
func (*GetTask) ProtoMessage()    {}
func (*GetTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *GetTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTask.Unmarshal(m, b)
}
func (m *GetTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTask.Marshal(b, m, deterministic)
}
func (m *GetTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTask.Merge(m, src)
}
func (m *GetTask) XXX_Size() int {
	return xxx_messageInfo_GetTask.Size(m)
}
func (m *GetTask) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTask.DiscardUnknown(m)
}

var xxx_messageInfo_GetTask proto.InternalMessageInfo

func (m *GetTask) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type InitResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

func (m *InitResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type ServiceMessage struct {
	Type                 ServiceMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=ServiceMessage_Type" json:"type,omitempty"`
	Request              *GetTask            `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Init                 *InitResponse       `protobuf:"bytes,3,opt,name=init,proto3" json:"init,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ServiceMessage) Reset()         { *m = ServiceMessage{} }
func (m *ServiceMessage) String() string { return proto.CompactTextString(m) }
func (*ServiceMessage) ProtoMessage()    {}
func (*ServiceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *ServiceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceMessage.Unmarshal(m, b)
}
func (m *ServiceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceMessage.Marshal(b, m, deterministic)
}
func (m *ServiceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceMessage.Merge(m, src)
}
func (m *ServiceMessage) XXX_Size() int {
	return xxx_messageInfo_ServiceMessage.Size(m)
}
func (m *ServiceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceMessage proto.InternalMessageInfo

func (m *ServiceMessage) GetType() ServiceMessage_Type {
	if m != nil {
		return m.Type
	}
	return ServiceMessage_GET_TASK
}

func (m *ServiceMessage) GetRequest() *GetTask {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ServiceMessage) GetInit() *InitResponse {
	if m != nil {
		return m.Init
	}
	return nil
}

func init() {
	proto.RegisterEnum("RequestMessage_Type", RequestMessage_Type_name, RequestMessage_Type_value)
	proto.RegisterEnum("ServiceMessage_Type", ServiceMessage_Type_name, ServiceMessage_Type_value)
	proto.RegisterType((*PutTask)(nil), "PutTask")
	proto.RegisterType((*Init)(nil), "Init")
	proto.RegisterType((*Statistic)(nil), "Statistic")
	proto.RegisterType((*ErrRate)(nil), "ErrRate")
	proto.RegisterType((*RequestMessage)(nil), "RequestMessage")
	proto.RegisterType((*GetTask)(nil), "GetTask")
	proto.RegisterType((*InitResponse)(nil), "InitResponse")
	proto.RegisterType((*ServiceMessage)(nil), "ServiceMessage")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x6f, 0xda, 0x4a,
	0x14, 0x7d, 0x03, 0x06, 0xc3, 0xe5, 0x23, 0x30, 0x8a, 0xf4, 0x48, 0xf4, 0x5e, 0x9b, 0x78, 0xd1,
	0xb0, 0x48, 0x50, 0x45, 0x2b, 0x75, 0x1d, 0x15, 0x2b, 0xb2, 0xa2, 0x26, 0x68, 0xec, 0xac, 0xad,
	0xa9, 0xb9, 0x89, 0x46, 0x7c, 0xd8, 0x99, 0x19, 0x47, 0xe5, 0x1f, 0xf4, 0x8f, 0x74, 0xd3, 0x6d,
	0xff, 0x60, 0x35, 0x63, 0x87, 0x00, 0x4d, 0x97, 0xf7, 0x9c, 0x39, 0xf7, 0xe3, 0x70, 0x0c, 0x74,
	0x14, 0xca, 0x27, 0x91, 0xe0, 0x28, 0x93, 0xa9, 0x4e, 0x3d, 0x1f, 0xdc, 0x69, 0xae, 0x23, 0xae,
	0xe6, 0xf4, 0x0d, 0x40, 0x92, 0x2b, 0x9d, 0x2e, 0x27, 0x5c, 0xf3, 0x01, 0x39, 0x21, 0xc3, 0x36,
	0xdb, 0x42, 0xe8, 0x31, 0x34, 0x34, 0x57, 0xf3, 0xbb, 0xbb, 0x60, 0x32, 0xa8, 0x9c, 0x90, 0x61,
	0x93, 0x6d, 0x6a, 0xef, 0x47, 0x05, 0x9c, 0x60, 0x25, 0x34, 0x3d, 0x83, 0xa6, 0x58, 0x09, 0x1d,
	0x2b, 0xcd, 0xb5, 0xed, 0xd1, 0x1a, 0xc3, 0x28, 0xd4, 0x5c, 0x0b, 0xa5, 0x45, 0xc2, 0x1a, 0x86,
	0x34, 0x25, 0xfd, 0x1f, 0x80, 0x27, 0x49, 0x9a, 0xaf, 0x74, 0x2c, 0x66, 0xb6, 0x5f, 0x9f, 0x35,
	0x4b, 0x24, 0x98, 0xd1, 0x7f, 0xc1, 0xe5, 0x99, 0x88, 0xe7, 0xb8, 0x1e, 0x54, 0xed, 0xac, 0x3a,
	0xcf, 0xc4, 0x35, 0xae, 0x0d, 0x21, 0xf3, 0x05, 0x1a, 0x91, 0x63, 0x45, 0x75, 0x53, 0x06, 0x33,
	0x7a, 0x0a, 0x6d, 0x89, 0xf7, 0x28, 0x71, 0x95, 0x60, 0x2c, 0xb2, 0x41, 0xcd, 0xca, 0x5a, 0x1b,
	0x2c, 0xc8, 0xe8, 0x11, 0x34, 0x1e, 0x73, 0xcc, 0xad, 0xb8, 0x6e, 0xc5, 0xae, 0xad, 0x83, 0x99,
	0x59, 0x47, 0xa1, 0x52, 0x22, 0x5d, 0x19, 0x12, 0xac, 0xb6, 0x59, 0x22, 0xc1, 0x8c, 0x9e, 0x03,
	0x5d, 0xf2, 0x6f, 0x62, 0x99, 0x2f, 0x63, 0x94, 0x32, 0x95, 0xb1, 0xe4, 0x1a, 0x07, 0xed, 0x13,
	0x32, 0x24, 0xac, 0x57, 0x32, 0xbe, 0x21, 0x18, 0xd7, 0x48, 0x07, 0xe0, 0x3e, 0xa1, 0x34, 0xd2,
	0x41, 0xa7, 0x18, 0x53, 0x96, 0xde, 0x2f, 0x02, 0xcd, 0x8d, 0x1b, 0xf4, 0x1d, 0x74, 0xf9, 0xd3,
	0x43, 0x24, 0x96, 0x18, 0xf1, 0xc5, 0x3c, 0xc4, 0xc4, 0x3a, 0x46, 0xd8, 0x1e, 0x4a, 0xcf, 0xa1,
	0x9f, 0xa1, 0x4c, 0x70, 0xa5, 0xc3, 0x3c, 0x49, 0x50, 0xa9, 0xfb, 0x7c, 0x61, 0x2d, 0x23, 0xec,
	0x4f, 0xa2, 0xec, 0x3a, 0x11, 0x7c, 0x61, 0x7a, 0x98, 0xae, 0xd5, 0x4d, 0xd7, 0x2d, 0x94, 0x0e,
	0xe1, 0xc0, 0xcc, 0x49, 0xf5, 0xcb, 0x43, 0xc7, 0x3e, 0xdc, 0x87, 0xbd, 0x4f, 0xe0, 0xfa, 0xb2,
	0x38, 0xed, 0x75, 0x23, 0xc8, 0xeb, 0x46, 0x78, 0xdf, 0x2b, 0xd0, 0x65, 0xf8, 0x98, 0xa3, 0xd2,
	0x5f, 0x50, 0x29, 0xfe, 0x80, 0x74, 0x08, 0x8e, 0x5e, 0x67, 0x85, 0xa4, 0x3b, 0x3e, 0x1c, 0xed,
	0xd2, 0xa3, 0x68, 0x9d, 0x21, 0xb3, 0x2f, 0xe8, 0x7f, 0xe0, 0x98, 0x7c, 0xd9, 0x43, 0x5b, 0xe3,
	0xc6, 0xa8, 0xcc, 0x29, 0xb3, 0x28, 0x3d, 0x02, 0xc7, 0x64, 0xc9, 0xde, 0xd6, 0x1a, 0xd7, 0x46,
	0x26, 0x7d, 0xcc, 0x42, 0x74, 0x08, 0x4d, 0xf5, 0xec, 0xb1, 0x3d, 0x69, 0x37, 0x83, 0x2f, 0x24,
	0xf5, 0xc0, 0xc5, 0xe2, 0x30, 0x1b, 0x17, 0x33, 0xa5, 0x3c, 0x94, 0x3d, 0x13, 0x9e, 0x0f, 0x8e,
	0x59, 0x8a, 0xb6, 0xa1, 0x31, 0xbd, 0x8b, 0xe2, 0xe8, 0x32, 0xbc, 0xee, 0xfd, 0x43, 0x1b, 0xe0,
	0x04, 0x37, 0x41, 0xd4, 0x23, 0xb4, 0x0f, 0x9d, 0xd0, 0x8f, 0xe2, 0x30, 0xba, 0x8c, 0x82, 0x30,
	0x0a, 0x3e, 0xf7, 0x2a, 0x94, 0x42, 0xd7, 0x40, 0x3e, 0x63, 0xb7, 0x2c, 0x66, 0x97, 0x91, 0xdf,
	0xab, 0x7a, 0x6f, 0xc1, 0xbd, 0xc2, 0xe2, 0x43, 0x3b, 0x84, 0x9a, 0x8d, 0xb9, 0xf5, 0xa0, 0xcf,
	0x8a, 0xc2, 0xbb, 0x80, 0xb6, 0xbd, 0x01, 0x55, 0x96, 0xae, 0x14, 0xee, 0x25, 0x92, 0xec, 0x25,
	0xd2, 0xfb, 0x49, 0xa0, 0x1b, 0x16, 0x9f, 0xf2, 0xdf, 0xac, 0xdd, 0xa5, 0xb7, 0xad, 0xf5, 0xc0,
	0x95, 0x85, 0xef, 0x1b, 0x77, 0xcb, 0xe5, 0xd8, 0x33, 0x41, 0x4f, 0x77, 0x0c, 0xee, 0x8c, 0xb6,
	0x97, 0x2b, 0x8c, 0xf6, 0xce, 0x5e, 0xac, 0xb9, 0xf2, 0x37, 0xd6, 0xf4, 0xa1, 0x63, 0xac, 0x89,
	0x99, 0x1f, 0x4e, 0x6f, 0x6f, 0x42, 0xbf, 0x47, 0xc6, 0x1f, 0xa1, 0x3a, 0x9d, 0x84, 0xf4, 0x02,
	0x6a, 0xa1, 0xe6, 0x52, 0xd3, 0x83, 0xbd, 0x9f, 0xfd, 0xf8, 0x60, 0x6f, 0xd9, 0x21, 0x79, 0x4f,
	0xbe, 0xd6, 0xed, 0x5f, 0xd4, 0x87, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x72, 0xdf, 0xb5, 0xe9,
	0xb3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PDSClient is the client API for PDS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PDSClient interface {
	Start(ctx context.Context, opts ...grpc.CallOption) (PDS_StartClient, error)
}

type pDSClient struct {
	cc *grpc.ClientConn
}

func NewPDSClient(cc *grpc.ClientConn) PDSClient {
	return &pDSClient{cc}
}

func (c *pDSClient) Start(ctx context.Context, opts ...grpc.CallOption) (PDS_StartClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PDS_serviceDesc.Streams[0], "/PDS/Start", opts...)
	if err != nil {
		return nil, err
	}
	x := &pDSStartClient{stream}
	return x, nil
}

type PDS_StartClient interface {
	Send(*RequestMessage) error
	Recv() (*ServiceMessage, error)
	grpc.ClientStream
}

type pDSStartClient struct {
	grpc.ClientStream
}

func (x *pDSStartClient) Send(m *RequestMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pDSStartClient) Recv() (*ServiceMessage, error) {
	m := new(ServiceMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PDSServer is the server API for PDS service.
type PDSServer interface {
	Start(PDS_StartServer) error
}

func RegisterPDSServer(s *grpc.Server, srv PDSServer) {
	s.RegisterService(&_PDS_serviceDesc, srv)
}

func _PDS_Start_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PDSServer).Start(&pDSStartServer{stream})
}

type PDS_StartServer interface {
	Send(*ServiceMessage) error
	Recv() (*RequestMessage, error)
	grpc.ServerStream
}

type pDSStartServer struct {
	grpc.ServerStream
}

func (x *pDSStartServer) Send(m *ServiceMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pDSStartServer) Recv() (*RequestMessage, error) {
	m := new(RequestMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PDS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PDS",
	HandlerType: (*PDSServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Start",
			Handler:       _PDS_Start_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
