syntax = "proto3";

option go_package = "github.com/voximplant/pds-sample-client/protogen";


message PutTask {
    bytes customData = 1;
    string taskUUID = 2;
}

enum BufferSizeTarget {
  VALUE = 0;
  OPERATOR = 1;
  AGENT = 2;
}

message Buffer {
  BufferSizeTarget size_target = 1;
  sint32 size_value = 2;
  double threshold_factor = 3;
}

message Init {
    enum PredictiveType {
        DEFAULT = 0;
        AR_OPTIMIZED = 1; // optimized abandonment rate solution
        BF_OPTIMIZED = 2; // optimized busy factor solution
        AR_SMALL_GROUP = 3;  // optimized abandonment rate solution for a small group of agents
        AR_AUTO_BALANCED = 4; // optimized abandonment rate solution with automatic adaptation to agent's count
    }
    Statistic init_stat = 1;
    sint32 account_id = 2;
    string api_key = 3;
    oneof rule {
        sint32 rule_id = 4;
        string rule_name = 18; // Rule name available only with application
    }
    string reference_ip = 5;
    sint32 queue_id = 6;
    string session_id = 10; // optional. use to continue processing after disconnect

    double maximum_waiting_time_ms = 11; // deprecated
    double maximum_error_rate = 12; // default: 0.02
    double minimum_busy_factor = 20; // default: 0.8

    PredictiveType predictive_type = 21;
    bool use_extended_task_status = 22;
    Buffer buffer = 23;

    sint32 version = 13;
    ACD acd_version = 15;
    enum ACD {
        V1 = 0;
        V2 = 1;
    }
    oneof application {
        sint32 application_id = 16; // for working with SQ
        string application_name = 19;
    }
    TaskMultiplier task_multiplier = 17; //for progressive
}

message Statistic {
    double avgTimeTalkSec = 1;
    double percentSuccessful = 2;
    double avgDialTimeSec = 3;
    double avgTotalTimeSec = 4;
}

message ErrRate {
    double maximum_error_rate = 1;
}

message BusyFactor {
    double minimum_busy_factor = 1;
}

message RequestMessage {
    enum Type {
        PUT_TASK = 0;
        INIT = 1;
        SET_STATISTIC = 2;
        SET_ERROR_RATE = 3;
        SET_TASK_MULTIPLIER = 4;
        SET_BUSY_FACTOR = 5;
        PING = 10;
    }
    Type type = 1;
    PutTask task = 2;
    Init init = 3;
    Statistic statistic = 4;
    ErrRate errRate = 5;
    TaskMultiplier taskMultiplier = 6;
    BusyFactor busyFactor = 7;
}


message GetTask {
    sint32 count = 1;
}

message InitResponse {
    string session_id = 1;
}

message TaskEvent {
    enum Type {
        STARTED = 0;
        CANCELLED = 1; // cancelled task happens on reconnect with old session id
        FAILED = 2; // failed to start
        UNKNOWN = 3; // we dont know task status
    }
    string taskUUID = 1;
    Type type = 2;
}

message ServiceMessage {
    enum Type {
        GET_TASK = 0;
        INIT_RESPONSE = 1;
        TASK_EVENT = 2;
        PONG = 10;
    }

    Type type = 1;
    GetTask request = 2;
    InitResponse init = 3;
    TaskEvent event = 4;
}


enum CompleteType {
    SUCCESS = 0;
    FAIL = 1;
    DIAL_COMPLETE = 2;
    TRANSFER = 3;
    AMD_STATUS = 4;
}


message TaskMultiplier {
    float multiplier = 1;
}

service PDS {
    rpc Start (stream RequestMessage) returns (stream ServiceMessage);

    rpc StartProgressive (stream RequestMessage) returns (stream ServiceMessage);
}