// PDS gRPC contract for the Voximplant Predictive Dialer System.
// Clients open a bidirectional stream, send INIT, then respond to GET_TASK
// with PUT_TASK messages and observe TASK_EVENT updates.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pds.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BufferSizeTarget int32

const (
	BufferSizeTarget_VALUE    BufferSizeTarget = 0
	BufferSizeTarget_OPERATOR BufferSizeTarget = 1
	BufferSizeTarget_AGENT    BufferSizeTarget = 2
	BufferSizeTarget_DYNAMIC  BufferSizeTarget = 3 // deprecated
	BufferSizeTarget_SMART    BufferSizeTarget = 4
)

// Enum value maps for BufferSizeTarget.
var (
	BufferSizeTarget_name = map[int32]string{
		0: "VALUE",
		1: "OPERATOR",
		2: "AGENT",
		3: "DYNAMIC",
		4: "SMART",
	}
	BufferSizeTarget_value = map[string]int32{
		"VALUE":    0,
		"OPERATOR": 1,
		"AGENT":    2,
		"DYNAMIC":  3,
		"SMART":    4,
	}
)

func (x BufferSizeTarget) Enum() *BufferSizeTarget {
	p := new(BufferSizeTarget)
	*p = x
	return p
}

func (x BufferSizeTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BufferSizeTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_pds_proto_enumTypes[0].Descriptor()
}

func (BufferSizeTarget) Type() protoreflect.EnumType {
	return &file_pds_proto_enumTypes[0]
}

func (x BufferSizeTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BufferSizeTarget.Descriptor instead.
func (BufferSizeTarget) EnumDescriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{0}
}

// Predictive dialing algorithm.
type Init_PredictiveType int32

const (
	Init_DEFAULT          Init_PredictiveType = 0
	Init_AR_OPTIMIZED     Init_PredictiveType = 1 // optimized abandonment rate solution
	Init_BF_OPTIMIZED     Init_PredictiveType = 2 // optimized busy factor solution
	Init_AR_SMALL_GROUP   Init_PredictiveType = 3 // optimized abandonment rate for a small agent group
	Init_AR_AUTO_BALANCED Init_PredictiveType = 4 // abandonment rate with automatic agent-count adaptation
)

// Enum value maps for Init_PredictiveType.
var (
	Init_PredictiveType_name = map[int32]string{
		0: "DEFAULT",
		1: "AR_OPTIMIZED",
		2: "BF_OPTIMIZED",
		3: "AR_SMALL_GROUP",
		4: "AR_AUTO_BALANCED",
	}
	Init_PredictiveType_value = map[string]int32{
		"DEFAULT":          0,
		"AR_OPTIMIZED":     1,
		"BF_OPTIMIZED":     2,
		"AR_SMALL_GROUP":   3,
		"AR_AUTO_BALANCED": 4,
	}
)

func (x Init_PredictiveType) Enum() *Init_PredictiveType {
	p := new(Init_PredictiveType)
	*p = x
	return p
}

func (x Init_PredictiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Init_PredictiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_pds_proto_enumTypes[1].Descriptor()
}

func (Init_PredictiveType) Type() protoreflect.EnumType {
	return &file_pds_proto_enumTypes[1]
}

func (x Init_PredictiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Init_PredictiveType.Descriptor instead.
func (Init_PredictiveType) EnumDescriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{3, 0}
}

type Init_StatisticsSource int32

const (
	Init_STATISTICS_SOURCE_UNSPECIFIED Init_StatisticsSource = 0
	Init_STATISTICS_SOURCE_INIT        Init_StatisticsSource = 1
	Init_STATISTICS_SOURCE_HISTORY     Init_StatisticsSource = 2
)

// Enum value maps for Init_StatisticsSource.
var (
	Init_StatisticsSource_name = map[int32]string{
		0: "STATISTICS_SOURCE_UNSPECIFIED",
		1: "STATISTICS_SOURCE_INIT",
		2: "STATISTICS_SOURCE_HISTORY",
	}
	Init_StatisticsSource_value = map[string]int32{
		"STATISTICS_SOURCE_UNSPECIFIED": 0,
		"STATISTICS_SOURCE_INIT":        1,
		"STATISTICS_SOURCE_HISTORY":     2,
	}
)

func (x Init_StatisticsSource) Enum() *Init_StatisticsSource {
	p := new(Init_StatisticsSource)
	*p = x
	return p
}

func (x Init_StatisticsSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Init_StatisticsSource) Descriptor() protoreflect.EnumDescriptor {
	return file_pds_proto_enumTypes[2].Descriptor()
}

func (Init_StatisticsSource) Type() protoreflect.EnumType {
	return &file_pds_proto_enumTypes[2]
}

func (x Init_StatisticsSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Init_StatisticsSource.Descriptor instead.
func (Init_StatisticsSource) EnumDescriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{3, 1}
}

type Init_ACD int32

const (
	Init_V1 Init_ACD = 0
	Init_V2 Init_ACD = 1
)

// Enum value maps for Init_ACD.
var (
	Init_ACD_name = map[int32]string{
		0: "V1",
		1: "V2",
	}
	Init_ACD_value = map[string]int32{
		"V1": 0,
		"V2": 1,
	}
)

func (x Init_ACD) Enum() *Init_ACD {
	p := new(Init_ACD)
	*p = x
	return p
}

func (x Init_ACD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Init_ACD) Descriptor() protoreflect.EnumDescriptor {
	return file_pds_proto_enumTypes[3].Descriptor()
}

func (Init_ACD) Type() protoreflect.EnumType {
	return &file_pds_proto_enumTypes[3]
}

func (x Init_ACD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Init_ACD.Descriptor instead.
func (Init_ACD) EnumDescriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{3, 2}
}

type RequestMessage_Type int32

const (
	RequestMessage_PUT_TASK            RequestMessage_Type = 0 // payload: task
	RequestMessage_INIT                RequestMessage_Type = 1 // payload: init
	RequestMessage_INIT_AUTOMATIC      RequestMessage_Type = 6 // payload: init_automatic
	RequestMessage_SET_STATISTIC       RequestMessage_Type = 2 // payload: statistic
	RequestMessage_SET_ERROR_RATE      RequestMessage_Type = 3 // payload: errRate
	RequestMessage_SET_TASK_MULTIPLIER RequestMessage_Type = 4 // payload: taskMultiplier
	RequestMessage_SET_BUSY_FACTOR     RequestMessage_Type = 5 // payload: busyFactor
	RequestMessage_FLUSH_BUFFER        RequestMessage_Type = 7
	RequestMessage_PING                RequestMessage_Type = 10 // keepalive; expect PONG
	RequestMessage_PUT_TASKS           RequestMessage_Type = 11 // payload: tasks (batch upload)
)

// Enum value maps for RequestMessage_Type.
var (
	RequestMessage_Type_name = map[int32]string{
		0:  "PUT_TASK",
		1:  "INIT",
		6:  "INIT_AUTOMATIC",
		2:  "SET_STATISTIC",
		3:  "SET_ERROR_RATE",
		4:  "SET_TASK_MULTIPLIER",
		5:  "SET_BUSY_FACTOR",
		7:  "FLUSH_BUFFER",
		10: "PING",
		11: "PUT_TASKS",
	}
	RequestMessage_Type_value = map[string]int32{
		"PUT_TASK":            0,
		"INIT":                1,
		"INIT_AUTOMATIC":      6,
		"SET_STATISTIC":       2,
		"SET_ERROR_RATE":      3,
		"SET_TASK_MULTIPLIER": 4,
		"SET_BUSY_FACTOR":     5,
		"FLUSH_BUFFER":        7,
		"PING":                10,
		"PUT_TASKS":           11,
	}
)

func (x RequestMessage_Type) Enum() *RequestMessage_Type {
	p := new(RequestMessage_Type)
	*p = x
	return p
}

func (x RequestMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pds_proto_enumTypes[4].Descriptor()
}

func (RequestMessage_Type) Type() protoreflect.EnumType {
	return &file_pds_proto_enumTypes[4]
}

func (x RequestMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestMessage_Type.Descriptor instead.
func (RequestMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{10, 0}
}

type TaskEvent_Type int32

const (
	TaskEvent_STARTED   TaskEvent_Type = 0
	TaskEvent_CANCELLED TaskEvent_Type = 1 // cancelled task happens on reconnect with old session id
	TaskEvent_FAILED    TaskEvent_Type = 2 // failed to start
	TaskEvent_UNKNOWN   TaskEvent_Type = 3 // we dont know task status
	TaskEvent_EXPIRED   TaskEvent_Type = 4
)

// Enum value maps for TaskEvent_Type.
var (
	TaskEvent_Type_name = map[int32]string{
		0: "STARTED",
		1: "CANCELLED",
		2: "FAILED",
		3: "UNKNOWN",
		4: "EXPIRED",
	}
	TaskEvent_Type_value = map[string]int32{
		"STARTED":   0,
		"CANCELLED": 1,
		"FAILED":    2,
		"UNKNOWN":   3,
		"EXPIRED":   4,
	}
)

func (x TaskEvent_Type) Enum() *TaskEvent_Type {
	p := new(TaskEvent_Type)
	*p = x
	return p
}

func (x TaskEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pds_proto_enumTypes[5].Descriptor()
}

func (TaskEvent_Type) Type() protoreflect.EnumType {
	return &file_pds_proto_enumTypes[5]
}

func (x TaskEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEvent_Type.Descriptor instead.
func (TaskEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{13, 0}
}

type ServiceMessage_Type int32

const (
	ServiceMessage_GET_TASK      ServiceMessage_Type = 0  // payload: request
	ServiceMessage_INIT_RESPONSE ServiceMessage_Type = 1  // payload: init
	ServiceMessage_TASK_EVENT    ServiceMessage_Type = 2  // payload: event
	ServiceMessage_PONG          ServiceMessage_Type = 10 // response to PING
)

// Enum value maps for ServiceMessage_Type.
var (
	ServiceMessage_Type_name = map[int32]string{
		0:  "GET_TASK",
		1:  "INIT_RESPONSE",
		2:  "TASK_EVENT",
		10: "PONG",
	}
	ServiceMessage_Type_value = map[string]int32{
		"GET_TASK":      0,
		"INIT_RESPONSE": 1,
		"TASK_EVENT":    2,
		"PONG":          10,
	}
)

func (x ServiceMessage_Type) Enum() *ServiceMessage_Type {
	p := new(ServiceMessage_Type)
	*p = x
	return p
}

func (x ServiceMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pds_proto_enumTypes[6].Descriptor()
}

func (ServiceMessage_Type) Type() protoreflect.EnumType {
	return &file_pds_proto_enumTypes[6]
}

func (x ServiceMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceMessage_Type.Descriptor instead.
func (ServiceMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{14, 0}
}

// PutTask is a single dialing job submitted by the client.
type PutTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque JSON payload forwarded to the VoxEngine scenario as users_data.
	CustomData []byte `protobuf:"bytes,1,opt,name=customData,proto3" json:"customData,omitempty"`
	// Client-generated task identifier used to correlate TASK_EVENT updates.
	TaskUUID         string `protobuf:"bytes,2,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"`
	MaxExecutionTime string `protobuf:"bytes,3,opt,name=max_execution_time,json=maxExecutionTime,proto3" json:"max_execution_time,omitempty"` // timeOnly
	MinExecutionTime string `protobuf:"bytes,6,opt,name=min_execution_time,json=minExecutionTime,proto3" json:"min_execution_time,omitempty"` // timeOnly
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PutTask) Reset() {
	*x = PutTask{}
	mi := &file_pds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTask) ProtoMessage() {}

func (x *PutTask) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTask.ProtoReflect.Descriptor instead.
func (*PutTask) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{0}
}

func (x *PutTask) GetCustomData() []byte {
	if x != nil {
		return x.CustomData
	}
	return nil
}

func (x *PutTask) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *PutTask) GetMaxExecutionTime() string {
	if x != nil {
		return x.MaxExecutionTime
	}
	return ""
}

func (x *PutTask) GetMinExecutionTime() string {
	if x != nil {
		return x.MinExecutionTime
	}
	return ""
}

// Buffer configures predictive dialer buffering behaviour.
type Buffer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SizeTarget      BufferSizeTarget       `protobuf:"varint,1,opt,name=size_target,json=sizeTarget,proto3,enum=BufferSizeTarget" json:"size_target,omitempty"`
	SizeValue       int32                  `protobuf:"zigzag32,2,opt,name=size_value,json=sizeValue,proto3" json:"size_value,omitempty"`
	ThresholdFactor float64                `protobuf:"fixed64,3,opt,name=threshold_factor,json=thresholdFactor,proto3" json:"threshold_factor,omitempty"`
	SizeFactor      float64                `protobuf:"fixed64,4,opt,name=size_factor,json=sizeFactor,proto3" json:"size_factor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Buffer) Reset() {
	*x = Buffer{}
	mi := &file_pds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buffer) ProtoMessage() {}

func (x *Buffer) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buffer.ProtoReflect.Descriptor instead.
func (*Buffer) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{1}
}

func (x *Buffer) GetSizeTarget() BufferSizeTarget {
	if x != nil {
		return x.SizeTarget
	}
	return BufferSizeTarget_VALUE
}

func (x *Buffer) GetSizeValue() int32 {
	if x != nil {
		return x.SizeValue
	}
	return 0
}

func (x *Buffer) GetThresholdFactor() float64 {
	if x != nil {
		return x.ThresholdFactor
	}
	return 0
}

func (x *Buffer) GetSizeFactor() float64 {
	if x != nil {
		return x.SizeFactor
	}
	return 0
}

// Model configures predictive dialer model parameters.
type Model struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	BoostEnabled                  bool                   `protobuf:"varint,1,opt,name=boost_enabled,json=boostEnabled,proto3" json:"boost_enabled,omitempty"`
	StartBoostDuration            int32                  `protobuf:"zigzag32,2,opt,name=start_boost_duration,json=startBoostDuration,proto3" json:"start_boost_duration,omitempty"`
	AfterHoldBoostDuration        int32                  `protobuf:"zigzag32,3,opt,name=after_hold_boost_duration,json=afterHoldBoostDuration,proto3" json:"after_hold_boost_duration,omitempty"`
	DynamicStatisticWindowEnabled bool                   `protobuf:"varint,4,opt,name=dynamic_statistic_window_enabled,json=dynamicStatisticWindowEnabled,proto3" json:"dynamic_statistic_window_enabled,omitempty"`
	OverloadControl               float64                `protobuf:"fixed64,5,opt,name=overload_control,json=overloadControl,proto3" json:"overload_control,omitempty"`
	Latency                       int32                  `protobuf:"zigzag32,6,opt,name=latency,proto3" json:"latency,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_pds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{2}
}

func (x *Model) GetBoostEnabled() bool {
	if x != nil {
		return x.BoostEnabled
	}
	return false
}

func (x *Model) GetStartBoostDuration() int32 {
	if x != nil {
		return x.StartBoostDuration
	}
	return 0
}

func (x *Model) GetAfterHoldBoostDuration() int32 {
	if x != nil {
		return x.AfterHoldBoostDuration
	}
	return 0
}

func (x *Model) GetDynamicStatisticWindowEnabled() bool {
	if x != nil {
		return x.DynamicStatisticWindowEnabled
	}
	return false
}

func (x *Model) GetOverloadControl() float64 {
	if x != nil {
		return x.OverloadControl
	}
	return 0
}

func (x *Model) GetLatency() int32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

// Init is the first client message on a new stream (RequestMessage.INIT).
type Init struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Initial dialer statistics used before enough live data is collected.
	InitStat         *Statistic            `protobuf:"bytes,1,opt,name=init_stat,json=initStat,proto3" json:"init_stat,omitempty"`
	StatisticsSource Init_StatisticsSource `protobuf:"varint,26,opt,name=statistics_source,json=statisticsSource,proto3,enum=Init_StatisticsSource" json:"statistics_source,omitempty"`
	AccountId        int32                 `protobuf:"zigzag32,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ApiKey           string                `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Types that are valid to be assigned to Rule:
	//
	//	*Init_RuleId
	//	*Init_RuleName
	Rule isInit_Rule `protobuf_oneof:"rule"`
	// Public IP used by Voximplant to reach the client side of the call.
	ReferenceIp    string `protobuf:"bytes,5,opt,name=reference_ip,json=referenceIp,proto3" json:"reference_ip,omitempty"`
	ServerLocation string `protobuf:"bytes,32,opt,name=server_location,json=serverLocation,proto3" json:"server_location,omitempty"`
	// SmartQueue identifier that receives connected calls.
	QueueId int32 `protobuf:"zigzag32,6,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	// Optional. Reuse after reconnect to keep accumulated session statistics.
	SessionId             string              `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MaximumWaitingTimeMs  float64             `protobuf:"fixed64,11,opt,name=maximum_waiting_time_ms,json=maximumWaitingTimeMs,proto3" json:"maximum_waiting_time_ms,omitempty"` // deprecated
	MaximumErrorRate      float64             `protobuf:"fixed64,12,opt,name=maximum_error_rate,json=maximumErrorRate,proto3" json:"maximum_error_rate,omitempty"`               // default: 0.02
	MinimumBusyFactor     float64             `protobuf:"fixed64,20,opt,name=minimum_busy_factor,json=minimumBusyFactor,proto3" json:"minimum_busy_factor,omitempty"`            // default: 0.8
	AmdBfForceLevel       float64             `protobuf:"fixed64,29,opt,name=amd_bf_force_level,json=amdBfForceLevel,proto3" json:"amd_bf_force_level,omitempty"`                // 26,27,28 is free
	PredictiveType        Init_PredictiveType `protobuf:"varint,21,opt,name=predictive_type,json=predictiveType,proto3,enum=Init_PredictiveType" json:"predictive_type,omitempty"`
	UseExtendedTaskStatus bool                `protobuf:"varint,22,opt,name=use_extended_task_status,json=useExtendedTaskStatus,proto3" json:"use_extended_task_status,omitempty"`
	Buffer                *Buffer             `protobuf:"bytes,23,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Model                 *Model              `protobuf:"bytes,24,opt,name=model,proto3" json:"model,omitempty"`
	Version               int32               `protobuf:"zigzag32,13,opt,name=version,proto3" json:"version,omitempty"`
	AcdVersion            Init_ACD            `protobuf:"varint,15,opt,name=acd_version,json=acdVersion,proto3,enum=Init_ACD" json:"acd_version,omitempty"`
	// Types that are valid to be assigned to Application:
	//
	//	*Init_ApplicationId
	//	*Init_ApplicationName
	Application isInit_Application `protobuf_oneof:"application"`
	// Required for progressive mode (StartProgressive).
	TaskMultiplier   *TaskMultiplier `protobuf:"bytes,17,opt,name=task_multiplier,json=taskMultiplier,proto3" json:"task_multiplier,omitempty"`
	Priority         int32           `protobuf:"zigzag32,30,opt,name=priority,proto3" json:"priority,omitempty"`
	MaxSimultaneous  int32           `protobuf:"zigzag32,31,opt,name=max_simultaneous,json=maxSimultaneous,proto3" json:"max_simultaneous,omitempty"`
	HitRateWindowSec int32           `protobuf:"zigzag32,34,opt,name=hit_rate_window_sec,json=hitRateWindowSec,proto3" json:"hit_rate_window_sec,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Init) Reset() {
	*x = Init{}
	mi := &file_pds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init) ProtoMessage() {}

func (x *Init) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init.ProtoReflect.Descriptor instead.
func (*Init) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{3}
}

func (x *Init) GetInitStat() *Statistic {
	if x != nil {
		return x.InitStat
	}
	return nil
}

func (x *Init) GetStatisticsSource() Init_StatisticsSource {
	if x != nil {
		return x.StatisticsSource
	}
	return Init_STATISTICS_SOURCE_UNSPECIFIED
}

func (x *Init) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Init) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Init) GetRule() isInit_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *Init) GetRuleId() int32 {
	if x != nil {
		if x, ok := x.Rule.(*Init_RuleId); ok {
			return x.RuleId
		}
	}
	return 0
}

func (x *Init) GetRuleName() string {
	if x != nil {
		if x, ok := x.Rule.(*Init_RuleName); ok {
			return x.RuleName
		}
	}
	return ""
}

func (x *Init) GetReferenceIp() string {
	if x != nil {
		return x.ReferenceIp
	}
	return ""
}

func (x *Init) GetServerLocation() string {
	if x != nil {
		return x.ServerLocation
	}
	return ""
}

func (x *Init) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *Init) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Init) GetMaximumWaitingTimeMs() float64 {
	if x != nil {
		return x.MaximumWaitingTimeMs
	}
	return 0
}

func (x *Init) GetMaximumErrorRate() float64 {
	if x != nil {
		return x.MaximumErrorRate
	}
	return 0
}

func (x *Init) GetMinimumBusyFactor() float64 {
	if x != nil {
		return x.MinimumBusyFactor
	}
	return 0
}

func (x *Init) GetAmdBfForceLevel() float64 {
	if x != nil {
		return x.AmdBfForceLevel
	}
	return 0
}

func (x *Init) GetPredictiveType() Init_PredictiveType {
	if x != nil {
		return x.PredictiveType
	}
	return Init_DEFAULT
}

func (x *Init) GetUseExtendedTaskStatus() bool {
	if x != nil {
		return x.UseExtendedTaskStatus
	}
	return false
}

func (x *Init) GetBuffer() *Buffer {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *Init) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Init) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Init) GetAcdVersion() Init_ACD {
	if x != nil {
		return x.AcdVersion
	}
	return Init_V1
}

func (x *Init) GetApplication() isInit_Application {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *Init) GetApplicationId() int32 {
	if x != nil {
		if x, ok := x.Application.(*Init_ApplicationId); ok {
			return x.ApplicationId
		}
	}
	return 0
}

func (x *Init) GetApplicationName() string {
	if x != nil {
		if x, ok := x.Application.(*Init_ApplicationName); ok {
			return x.ApplicationName
		}
	}
	return ""
}

func (x *Init) GetTaskMultiplier() *TaskMultiplier {
	if x != nil {
		return x.TaskMultiplier
	}
	return nil
}

func (x *Init) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Init) GetMaxSimultaneous() int32 {
	if x != nil {
		return x.MaxSimultaneous
	}
	return 0
}

func (x *Init) GetHitRateWindowSec() int32 {
	if x != nil {
		return x.HitRateWindowSec
	}
	return 0
}

type isInit_Rule interface {
	isInit_Rule()
}

type Init_RuleId struct {
	RuleId int32 `protobuf:"zigzag32,4,opt,name=rule_id,json=ruleId,proto3,oneof"`
}

type Init_RuleName struct {
	RuleName string `protobuf:"bytes,18,opt,name=rule_name,json=ruleName,proto3,oneof"` // Rule name available only with application
}

func (*Init_RuleId) isInit_Rule() {}

func (*Init_RuleName) isInit_Rule() {}

type isInit_Application interface {
	isInit_Application()
}

type Init_ApplicationId struct {
	ApplicationId int32 `protobuf:"zigzag32,16,opt,name=application_id,json=applicationId,proto3,oneof"` // for working with SQ
}

type Init_ApplicationName struct {
	ApplicationName string `protobuf:"bytes,19,opt,name=application_name,json=applicationName,proto3,oneof"`
}

func (*Init_ApplicationId) isInit_Application() {}

func (*Init_ApplicationName) isInit_Application() {}

// InitAutomatic is an alternative initialization payload (RequestMessage.INIT_AUTOMATIC).
type InitAutomatic struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccountId      int32                  `protobuf:"zigzag32,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ApiKey         string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ReferenceIp    string                 `protobuf:"bytes,4,opt,name=reference_ip,json=referenceIp,proto3" json:"reference_ip,omitempty"`
	ServerLocation string                 `protobuf:"bytes,11,opt,name=server_location,json=serverLocation,proto3" json:"server_location,omitempty"`
	// Types that are valid to be assigned to Rule:
	//
	//	*InitAutomatic_RuleId
	//	*InitAutomatic_RuleName
	Rule isInitAutomatic_Rule `protobuf_oneof:"rule"`
	// Types that are valid to be assigned to Application:
	//
	//	*InitAutomatic_ApplicationId
	//	*InitAutomatic_ApplicationName
	Application     isInitAutomatic_Application `protobuf_oneof:"application"`
	Priority        int32                       `protobuf:"zigzag32,9,opt,name=priority,proto3" json:"priority,omitempty"`
	MaxSimultaneous int32                       `protobuf:"zigzag32,10,opt,name=max_simultaneous,json=maxSimultaneous,proto3" json:"max_simultaneous,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitAutomatic) Reset() {
	*x = InitAutomatic{}
	mi := &file_pds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAutomatic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAutomatic) ProtoMessage() {}

func (x *InitAutomatic) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAutomatic.ProtoReflect.Descriptor instead.
func (*InitAutomatic) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{4}
}

func (x *InitAutomatic) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitAutomatic) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *InitAutomatic) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *InitAutomatic) GetReferenceIp() string {
	if x != nil {
		return x.ReferenceIp
	}
	return ""
}

func (x *InitAutomatic) GetServerLocation() string {
	if x != nil {
		return x.ServerLocation
	}
	return ""
}

func (x *InitAutomatic) GetRule() isInitAutomatic_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *InitAutomatic) GetRuleId() int32 {
	if x != nil {
		if x, ok := x.Rule.(*InitAutomatic_RuleId); ok {
			return x.RuleId
		}
	}
	return 0
}

func (x *InitAutomatic) GetRuleName() string {
	if x != nil {
		if x, ok := x.Rule.(*InitAutomatic_RuleName); ok {
			return x.RuleName
		}
	}
	return ""
}

func (x *InitAutomatic) GetApplication() isInitAutomatic_Application {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *InitAutomatic) GetApplicationId() int32 {
	if x != nil {
		if x, ok := x.Application.(*InitAutomatic_ApplicationId); ok {
			return x.ApplicationId
		}
	}
	return 0
}

func (x *InitAutomatic) GetApplicationName() string {
	if x != nil {
		if x, ok := x.Application.(*InitAutomatic_ApplicationName); ok {
			return x.ApplicationName
		}
	}
	return ""
}

func (x *InitAutomatic) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *InitAutomatic) GetMaxSimultaneous() int32 {
	if x != nil {
		return x.MaxSimultaneous
	}
	return 0
}

type isInitAutomatic_Rule interface {
	isInitAutomatic_Rule()
}

type InitAutomatic_RuleId struct {
	RuleId int32 `protobuf:"zigzag32,5,opt,name=rule_id,json=ruleId,proto3,oneof"`
}

type InitAutomatic_RuleName struct {
	RuleName string `protobuf:"bytes,6,opt,name=rule_name,json=ruleName,proto3,oneof"`
}

func (*InitAutomatic_RuleId) isInitAutomatic_Rule() {}

func (*InitAutomatic_RuleName) isInitAutomatic_Rule() {}

type isInitAutomatic_Application interface {
	isInitAutomatic_Application()
}

type InitAutomatic_ApplicationId struct {
	ApplicationId int32 `protobuf:"zigzag32,7,opt,name=application_id,json=applicationId,proto3,oneof"`
}

type InitAutomatic_ApplicationName struct {
	ApplicationName string `protobuf:"bytes,8,opt,name=application_name,json=applicationName,proto3,oneof"`
}

func (*InitAutomatic_ApplicationId) isInitAutomatic_Application() {}

func (*InitAutomatic_ApplicationName) isInitAutomatic_Application() {}

// Statistic holds dialer performance inputs for INIT / SET_STATISTIC.
type Statistic struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AvgTimeTalkSec    float64                `protobuf:"fixed64,1,opt,name=avgTimeTalkSec,proto3" json:"avgTimeTalkSec,omitempty"`
	PercentSuccessful float64                `protobuf:"fixed64,2,opt,name=percentSuccessful,proto3" json:"percentSuccessful,omitempty"`
	AvgDialTimeSec    float64                `protobuf:"fixed64,3,opt,name=avgDialTimeSec,proto3" json:"avgDialTimeSec,omitempty"`
	AvgTotalTimeSec   float64                `protobuf:"fixed64,4,opt,name=avgTotalTimeSec,proto3" json:"avgTotalTimeSec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Statistic) Reset() {
	*x = Statistic{}
	mi := &file_pds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic) ProtoMessage() {}

func (x *Statistic) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic.ProtoReflect.Descriptor instead.
func (*Statistic) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{5}
}

func (x *Statistic) GetAvgTimeTalkSec() float64 {
	if x != nil {
		return x.AvgTimeTalkSec
	}
	return 0
}

func (x *Statistic) GetPercentSuccessful() float64 {
	if x != nil {
		return x.PercentSuccessful
	}
	return 0
}

func (x *Statistic) GetAvgDialTimeSec() float64 {
	if x != nil {
		return x.AvgDialTimeSec
	}
	return 0
}

func (x *Statistic) GetAvgTotalTimeSec() float64 {
	if x != nil {
		return x.AvgTotalTimeSec
	}
	return 0
}

// ErrRate updates the maximum abandonment / error rate at runtime.
type ErrRate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaximumErrorRate float64                `protobuf:"fixed64,1,opt,name=maximum_error_rate,json=maximumErrorRate,proto3" json:"maximum_error_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ErrRate) Reset() {
	*x = ErrRate{}
	mi := &file_pds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrRate) ProtoMessage() {}

func (x *ErrRate) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrRate.ProtoReflect.Descriptor instead.
func (*ErrRate) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{6}
}

func (x *ErrRate) GetMaximumErrorRate() float64 {
	if x != nil {
		return x.MaximumErrorRate
	}
	return 0
}

// BusyFactor updates the minimum busy-factor target at runtime.
type BusyFactor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MinimumBusyFactor float64                `protobuf:"fixed64,1,opt,name=minimum_busy_factor,json=minimumBusyFactor,proto3" json:"minimum_busy_factor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BusyFactor) Reset() {
	*x = BusyFactor{}
	mi := &file_pds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusyFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusyFactor) ProtoMessage() {}

func (x *BusyFactor) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusyFactor.ProtoReflect.Descriptor instead.
func (*BusyFactor) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{7}
}

func (x *BusyFactor) GetMinimumBusyFactor() float64 {
	if x != nil {
		return x.MinimumBusyFactor
	}
	return 0
}

type MaxSimultaneousTasks struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxSimultaneous int32                  `protobuf:"zigzag32,1,opt,name=max_simultaneous,json=maxSimultaneous,proto3" json:"max_simultaneous,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MaxSimultaneousTasks) Reset() {
	*x = MaxSimultaneousTasks{}
	mi := &file_pds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxSimultaneousTasks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxSimultaneousTasks) ProtoMessage() {}

func (x *MaxSimultaneousTasks) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxSimultaneousTasks.ProtoReflect.Descriptor instead.
func (*MaxSimultaneousTasks) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{8}
}

func (x *MaxSimultaneousTasks) GetMaxSimultaneous() int32 {
	if x != nil {
		return x.MaxSimultaneous
	}
	return 0
}

// PutTasks is a batch of dialing jobs (RequestMessage.PUT_TASKS).
type PutTasks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*PutTask             `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTasks) Reset() {
	*x = PutTasks{}
	mi := &file_pds_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTasks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTasks) ProtoMessage() {}

func (x *PutTasks) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTasks.ProtoReflect.Descriptor instead.
func (*PutTasks) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{9}
}

func (x *PutTasks) GetTasks() []*PutTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// RequestMessage is a client → server envelope on the PDS stream.
type RequestMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           RequestMessage_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=RequestMessage_Type" json:"type,omitempty"`
	Task           *PutTask               `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Init           *Init                  `protobuf:"bytes,3,opt,name=init,proto3" json:"init,omitempty"`
	InitAutomatic  *InitAutomatic         `protobuf:"bytes,8,opt,name=init_automatic,json=initAutomatic,proto3" json:"init_automatic,omitempty"`
	Statistic      *Statistic             `protobuf:"bytes,4,opt,name=statistic,proto3" json:"statistic,omitempty"`
	ErrRate        *ErrRate               `protobuf:"bytes,5,opt,name=errRate,proto3" json:"errRate,omitempty"`
	TaskMultiplier *TaskMultiplier        `protobuf:"bytes,6,opt,name=taskMultiplier,proto3" json:"taskMultiplier,omitempty"`
	BusyFactor     *BusyFactor            `protobuf:"bytes,7,opt,name=busyFactor,proto3" json:"busyFactor,omitempty"`
	Tasks          *PutTasks              `protobuf:"bytes,9,opt,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_pds_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{10}
}

func (x *RequestMessage) GetType() RequestMessage_Type {
	if x != nil {
		return x.Type
	}
	return RequestMessage_PUT_TASK
}

func (x *RequestMessage) GetTask() *PutTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *RequestMessage) GetInit() *Init {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *RequestMessage) GetInitAutomatic() *InitAutomatic {
	if x != nil {
		return x.InitAutomatic
	}
	return nil
}

func (x *RequestMessage) GetStatistic() *Statistic {
	if x != nil {
		return x.Statistic
	}
	return nil
}

func (x *RequestMessage) GetErrRate() *ErrRate {
	if x != nil {
		return x.ErrRate
	}
	return nil
}

func (x *RequestMessage) GetTaskMultiplier() *TaskMultiplier {
	if x != nil {
		return x.TaskMultiplier
	}
	return nil
}

func (x *RequestMessage) GetBusyFactor() *BusyFactor {
	if x != nil {
		return x.BusyFactor
	}
	return nil
}

func (x *RequestMessage) GetTasks() *PutTasks {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// GetTask asks the client to submit the given number of tasks.
type GetTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact number of PUT_TASK messages the client must send next.
	Count int32 `protobuf:"zigzag32,1,opt,name=count,proto3" json:"count,omitempty"`
	// Agent IDs currently in Ready status.
	UserIds       []int64 `protobuf:"zigzag64,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTask) Reset() {
	*x = GetTask{}
	mi := &file_pds_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTask) ProtoMessage() {}

func (x *GetTask) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTask.ProtoReflect.Descriptor instead.
func (*GetTask) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{11}
}

func (x *GetTask) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetTask) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// InitResponse acknowledges a successful INIT.
type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Persist and reuse on reconnect to keep session statistics.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_pds_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{12}
}

func (x *InitResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// TaskEvent reports the lifecycle of a previously submitted task.
type TaskEvent struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	TaskUUID                    string                 `protobuf:"bytes,1,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"`
	Type                        TaskEvent_Type         `protobuf:"varint,2,opt,name=type,proto3,enum=TaskEvent_Type" json:"type,omitempty"`
	MsCheckUrl                  string                 `protobuf:"bytes,3,opt,name=ms_check_url,json=msCheckUrl,proto3" json:"ms_check_url,omitempty"`
	MsAccessUrl                 string                 `protobuf:"bytes,4,opt,name=ms_access_url,json=msAccessUrl,proto3" json:"ms_access_url,omitempty"`
	StartedAt                   string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CallSessionHistoryId        int64                  `protobuf:"varint,6,opt,name=call_session_history_id,json=callSessionHistoryId,proto3" json:"call_session_history_id,omitempty"`
	MediaSessionAccessSecureUrl string                 `protobuf:"bytes,7,opt,name=media_session_access_secure_url,json=mediaSessionAccessSecureUrl,proto3" json:"media_session_access_secure_url,omitempty"`
	Result                      int64                  `protobuf:"varint,8,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_pds_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{13}
}

func (x *TaskEvent) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *TaskEvent) GetType() TaskEvent_Type {
	if x != nil {
		return x.Type
	}
	return TaskEvent_STARTED
}

func (x *TaskEvent) GetMsCheckUrl() string {
	if x != nil {
		return x.MsCheckUrl
	}
	return ""
}

func (x *TaskEvent) GetMsAccessUrl() string {
	if x != nil {
		return x.MsAccessUrl
	}
	return ""
}

func (x *TaskEvent) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *TaskEvent) GetCallSessionHistoryId() int64 {
	if x != nil {
		return x.CallSessionHistoryId
	}
	return 0
}

func (x *TaskEvent) GetMediaSessionAccessSecureUrl() string {
	if x != nil {
		return x.MediaSessionAccessSecureUrl
	}
	return ""
}

func (x *TaskEvent) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// ServiceMessage is a server → client envelope on the PDS stream.
type ServiceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServiceMessage_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=ServiceMessage_Type" json:"type,omitempty"`
	Request       *GetTask               `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Init          *InitResponse          `protobuf:"bytes,3,opt,name=init,proto3" json:"init,omitempty"`
	Event         *TaskEvent             `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMessage) Reset() {
	*x = ServiceMessage{}
	mi := &file_pds_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMessage) ProtoMessage() {}

func (x *ServiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMessage.ProtoReflect.Descriptor instead.
func (*ServiceMessage) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{14}
}

func (x *ServiceMessage) GetType() ServiceMessage_Type {
	if x != nil {
		return x.Type
	}
	return ServiceMessage_GET_TASK
}

func (x *ServiceMessage) GetRequest() *GetTask {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ServiceMessage) GetInit() *InitResponse {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *ServiceMessage) GetEvent() *TaskEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// TaskMultiplier controls progressive dialing intensity.
type TaskMultiplier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multiplier    float32                `protobuf:"fixed32,1,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMultiplier) Reset() {
	*x = TaskMultiplier{}
	mi := &file_pds_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMultiplier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMultiplier) ProtoMessage() {}

func (x *TaskMultiplier) ProtoReflect() protoreflect.Message {
	mi := &file_pds_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMultiplier.ProtoReflect.Descriptor instead.
func (*TaskMultiplier) Descriptor() ([]byte, []int) {
	return file_pds_proto_rawDescGZIP(), []int{15}
}

func (x *TaskMultiplier) GetMultiplier() float32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

var File_pds_proto protoreflect.FileDescriptor

const file_pds_proto_rawDesc = "" +
	"\n" +
	"\tpds.proto\"\xa1\x01\n" +
	"\aPutTask\x12\x1e\n" +
	"\n" +
	"customData\x18\x01 \x01(\fR\n" +
	"customData\x12\x1a\n" +
	"\btaskUUID\x18\x02 \x01(\tR\btaskUUID\x12,\n" +
	"\x12max_execution_time\x18\x03 \x01(\tR\x10maxExecutionTime\x12,\n" +
	"\x12min_execution_time\x18\x06 \x01(\tR\x10minExecutionTime\"\xa7\x01\n" +
	"\x06Buffer\x122\n" +
	"\vsize_target\x18\x01 \x01(\x0e2\x11.BufferSizeTargetR\n" +
	"sizeTarget\x12\x1d\n" +
	"\n" +
	"size_value\x18\x02 \x01(\x11R\tsizeValue\x12)\n" +
	"\x10threshold_factor\x18\x03 \x01(\x01R\x0fthresholdFactor\x12\x1f\n" +
	"\vsize_factor\x18\x04 \x01(\x01R\n" +
	"sizeFactor\"\xa7\x02\n" +
	"\x05Model\x12#\n" +
	"\rboost_enabled\x18\x01 \x01(\bR\fboostEnabled\x120\n" +
	"\x14start_boost_duration\x18\x02 \x01(\x11R\x12startBoostDuration\x129\n" +
	"\x19after_hold_boost_duration\x18\x03 \x01(\x11R\x16afterHoldBoostDuration\x12G\n" +
	" dynamic_statistic_window_enabled\x18\x04 \x01(\bR\x1ddynamicStatisticWindowEnabled\x12)\n" +
	"\x10overload_control\x18\x05 \x01(\x01R\x0foverloadControl\x12\x18\n" +
	"\alatency\x18\x06 \x01(\x11R\alatency\"\xbe\n" +
	"\n" +
	"\x04Init\x12'\n" +
	"\tinit_stat\x18\x01 \x01(\v2\n" +
	".StatisticR\binitStat\x12C\n" +
	"\x11statistics_source\x18\x1a \x01(\x0e2\x16.Init.StatisticsSourceR\x10statisticsSource\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x11R\taccountId\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x19\n" +
	"\arule_id\x18\x04 \x01(\x11H\x00R\x06ruleId\x12\x1d\n" +
	"\trule_name\x18\x12 \x01(\tH\x00R\bruleName\x12!\n" +
	"\freference_ip\x18\x05 \x01(\tR\vreferenceIp\x12'\n" +
	"\x0fserver_location\x18  \x01(\tR\x0eserverLocation\x12\x19\n" +
	"\bqueue_id\x18\x06 \x01(\x11R\aqueueId\x12\x1d\n" +
	"\n" +
	"session_id\x18\n" +
	" \x01(\tR\tsessionId\x125\n" +
	"\x17maximum_waiting_time_ms\x18\v \x01(\x01R\x14maximumWaitingTimeMs\x12,\n" +
	"\x12maximum_error_rate\x18\f \x01(\x01R\x10maximumErrorRate\x12.\n" +
	"\x13minimum_busy_factor\x18\x14 \x01(\x01R\x11minimumBusyFactor\x12+\n" +
	"\x12amd_bf_force_level\x18\x1d \x01(\x01R\x0famdBfForceLevel\x12=\n" +
	"\x0fpredictive_type\x18\x15 \x01(\x0e2\x14.Init.PredictiveTypeR\x0epredictiveType\x127\n" +
	"\x18use_extended_task_status\x18\x16 \x01(\bR\x15useExtendedTaskStatus\x12\x1f\n" +
	"\x06buffer\x18\x17 \x01(\v2\a.BufferR\x06buffer\x12\x1c\n" +
	"\x05model\x18\x18 \x01(\v2\x06.ModelR\x05model\x12\x18\n" +
	"\aversion\x18\r \x01(\x11R\aversion\x12*\n" +
	"\vacd_version\x18\x0f \x01(\x0e2\t.Init.ACDR\n" +
	"acdVersion\x12'\n" +
	"\x0eapplication_id\x18\x10 \x01(\x11H\x01R\rapplicationId\x12+\n" +
	"\x10application_name\x18\x13 \x01(\tH\x01R\x0fapplicationName\x128\n" +
	"\x0ftask_multiplier\x18\x11 \x01(\v2\x0f.TaskMultiplierR\x0etaskMultiplier\x12\x1a\n" +
	"\bpriority\x18\x1e \x01(\x11R\bpriority\x12)\n" +
	"\x10max_simultaneous\x18\x1f \x01(\x11R\x0fmaxSimultaneous\x12-\n" +
	"\x13hit_rate_window_sec\x18\" \x01(\x11R\x10hitRateWindowSec\"k\n" +
	"\x0ePredictiveType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\x10\n" +
	"\fAR_OPTIMIZED\x10\x01\x12\x10\n" +
	"\fBF_OPTIMIZED\x10\x02\x12\x12\n" +
	"\x0eAR_SMALL_GROUP\x10\x03\x12\x14\n" +
	"\x10AR_AUTO_BALANCED\x10\x04\"p\n" +
	"\x10StatisticsSource\x12!\n" +
	"\x1dSTATISTICS_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STATISTICS_SOURCE_INIT\x10\x01\x12\x1d\n" +
	"\x19STATISTICS_SOURCE_HISTORY\x10\x02\"\x15\n" +
	"\x03ACD\x12\x06\n" +
	"\x02V1\x10\x00\x12\x06\n" +
	"\x02V2\x10\x01B\x06\n" +
	"\x04ruleB\r\n" +
	"\vapplication\"\xa0\x03\n" +
	"\rInitAutomatic\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x11R\taccountId\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12!\n" +
	"\freference_ip\x18\x04 \x01(\tR\vreferenceIp\x12'\n" +
	"\x0fserver_location\x18\v \x01(\tR\x0eserverLocation\x12\x19\n" +
	"\arule_id\x18\x05 \x01(\x11H\x00R\x06ruleId\x12\x1d\n" +
	"\trule_name\x18\x06 \x01(\tH\x00R\bruleName\x12'\n" +
	"\x0eapplication_id\x18\a \x01(\x11H\x01R\rapplicationId\x12+\n" +
	"\x10application_name\x18\b \x01(\tH\x01R\x0fapplicationName\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x11R\bpriority\x12)\n" +
	"\x10max_simultaneous\x18\n" +
	" \x01(\x11R\x0fmaxSimultaneousB\x06\n" +
	"\x04ruleB\r\n" +
	"\vapplication\"\xb3\x01\n" +
	"\tStatistic\x12&\n" +
	"\x0eavgTimeTalkSec\x18\x01 \x01(\x01R\x0eavgTimeTalkSec\x12,\n" +
	"\x11percentSuccessful\x18\x02 \x01(\x01R\x11percentSuccessful\x12&\n" +
	"\x0eavgDialTimeSec\x18\x03 \x01(\x01R\x0eavgDialTimeSec\x12(\n" +
	"\x0favgTotalTimeSec\x18\x04 \x01(\x01R\x0favgTotalTimeSec\"7\n" +
	"\aErrRate\x12,\n" +
	"\x12maximum_error_rate\x18\x01 \x01(\x01R\x10maximumErrorRate\"<\n" +
	"\n" +
	"BusyFactor\x12.\n" +
	"\x13minimum_busy_factor\x18\x01 \x01(\x01R\x11minimumBusyFactor\"A\n" +
	"\x14MaxSimultaneousTasks\x12)\n" +
	"\x10max_simultaneous\x18\x01 \x01(\x11R\x0fmaxSimultaneous\"*\n" +
	"\bPutTasks\x12\x1e\n" +
	"\x05tasks\x18\x01 \x03(\v2\b.PutTaskR\x05tasks\"\xb4\x04\n" +
	"\x0eRequestMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.RequestMessage.TypeR\x04type\x12\x1c\n" +
	"\x04task\x18\x02 \x01(\v2\b.PutTaskR\x04task\x12\x19\n" +
	"\x04init\x18\x03 \x01(\v2\x05.InitR\x04init\x125\n" +
	"\x0einit_automatic\x18\b \x01(\v2\x0e.InitAutomaticR\rinitAutomatic\x12(\n" +
	"\tstatistic\x18\x04 \x01(\v2\n" +
	".StatisticR\tstatistic\x12\"\n" +
	"\aerrRate\x18\x05 \x01(\v2\b.ErrRateR\aerrRate\x127\n" +
	"\x0etaskMultiplier\x18\x06 \x01(\v2\x0f.TaskMultiplierR\x0etaskMultiplier\x12+\n" +
	"\n" +
	"busyFactor\x18\a \x01(\v2\v.BusyFactorR\n" +
	"busyFactor\x12\x1f\n" +
	"\x05tasks\x18\t \x01(\v2\t.PutTasksR\x05tasks\"\xb2\x01\n" +
	"\x04Type\x12\f\n" +
	"\bPUT_TASK\x10\x00\x12\b\n" +
	"\x04INIT\x10\x01\x12\x12\n" +
	"\x0eINIT_AUTOMATIC\x10\x06\x12\x11\n" +
	"\rSET_STATISTIC\x10\x02\x12\x12\n" +
	"\x0eSET_ERROR_RATE\x10\x03\x12\x17\n" +
	"\x13SET_TASK_MULTIPLIER\x10\x04\x12\x13\n" +
	"\x0fSET_BUSY_FACTOR\x10\x05\x12\x10\n" +
	"\fFLUSH_BUFFER\x10\a\x12\b\n" +
	"\x04PING\x10\n" +
	"\x12\r\n" +
	"\tPUT_TASKS\x10\v\":\n" +
	"\aGetTask\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x11R\x05count\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x12R\auserIds\"-\n" +
	"\fInitResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x90\x03\n" +
	"\tTaskEvent\x12\x1a\n" +
	"\btaskUUID\x18\x01 \x01(\tR\btaskUUID\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.TaskEvent.TypeR\x04type\x12 \n" +
	"\fms_check_url\x18\x03 \x01(\tR\n" +
	"msCheckUrl\x12\"\n" +
	"\rms_access_url\x18\x04 \x01(\tR\vmsAccessUrl\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x125\n" +
	"\x17call_session_history_id\x18\x06 \x01(\x03R\x14callSessionHistoryId\x12D\n" +
	"\x1fmedia_session_access_secure_url\x18\a \x01(\tR\x1bmediaSessionAccessSecureUrl\x12\x16\n" +
	"\x06result\x18\b \x01(\x03R\x06result\"H\n" +
	"\x04Type\x12\v\n" +
	"\aSTARTED\x10\x00\x12\r\n" +
	"\tCANCELLED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\v\n" +
	"\aUNKNOWN\x10\x03\x12\v\n" +
	"\aEXPIRED\x10\x04\"\xe6\x01\n" +
	"\x0eServiceMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.ServiceMessage.TypeR\x04type\x12\"\n" +
	"\arequest\x18\x02 \x01(\v2\b.GetTaskR\arequest\x12!\n" +
	"\x04init\x18\x03 \x01(\v2\r.InitResponseR\x04init\x12 \n" +
	"\x05event\x18\x04 \x01(\v2\n" +
	".TaskEventR\x05event\"A\n" +
	"\x04Type\x12\f\n" +
	"\bGET_TASK\x10\x00\x12\x11\n" +
	"\rINIT_RESPONSE\x10\x01\x12\x0e\n" +
	"\n" +
	"TASK_EVENT\x10\x02\x12\b\n" +
	"\x04PONG\x10\n" +
	"\"0\n" +
	"\x0eTaskMultiplier\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x01 \x01(\x02R\n" +
	"multiplier*N\n" +
	"\x10BufferSizeTarget\x12\t\n" +
	"\x05VALUE\x10\x00\x12\f\n" +
	"\bOPERATOR\x10\x01\x12\t\n" +
	"\x05AGENT\x10\x02\x12\v\n" +
	"\aDYNAMIC\x10\x03\x12\t\n" +
	"\x05SMART\x10\x042n\n" +
	"\x03PDS\x12-\n" +
	"\x05Start\x12\x0f.RequestMessage\x1a\x0f.ServiceMessage(\x010\x01\x128\n" +
	"\x10StartProgressive\x12\x0f.RequestMessage\x1a\x0f.ServiceMessage(\x010\x01B-Z+github.com/voximplant/pds-sample-client/apib\x06proto3"

var (
	file_pds_proto_rawDescOnce sync.Once
	file_pds_proto_rawDescData []byte
)

func file_pds_proto_rawDescGZIP() []byte {
	file_pds_proto_rawDescOnce.Do(func() {
		file_pds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pds_proto_rawDesc), len(file_pds_proto_rawDesc)))
	})
	return file_pds_proto_rawDescData
}

var file_pds_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_pds_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pds_proto_goTypes = []any{
	(BufferSizeTarget)(0),        // 0: BufferSizeTarget
	(Init_PredictiveType)(0),     // 1: Init.PredictiveType
	(Init_StatisticsSource)(0),   // 2: Init.StatisticsSource
	(Init_ACD)(0),                // 3: Init.ACD
	(RequestMessage_Type)(0),     // 4: RequestMessage.Type
	(TaskEvent_Type)(0),          // 5: TaskEvent.Type
	(ServiceMessage_Type)(0),     // 6: ServiceMessage.Type
	(*PutTask)(nil),              // 7: PutTask
	(*Buffer)(nil),               // 8: Buffer
	(*Model)(nil),                // 9: Model
	(*Init)(nil),                 // 10: Init
	(*InitAutomatic)(nil),        // 11: InitAutomatic
	(*Statistic)(nil),            // 12: Statistic
	(*ErrRate)(nil),              // 13: ErrRate
	(*BusyFactor)(nil),           // 14: BusyFactor
	(*MaxSimultaneousTasks)(nil), // 15: MaxSimultaneousTasks
	(*PutTasks)(nil),             // 16: PutTasks
	(*RequestMessage)(nil),       // 17: RequestMessage
	(*GetTask)(nil),              // 18: GetTask
	(*InitResponse)(nil),         // 19: InitResponse
	(*TaskEvent)(nil),            // 20: TaskEvent
	(*ServiceMessage)(nil),       // 21: ServiceMessage
	(*TaskMultiplier)(nil),       // 22: TaskMultiplier
}
var file_pds_proto_depIdxs = []int32{
	0,  // 0: Buffer.size_target:type_name -> BufferSizeTarget
	12, // 1: Init.init_stat:type_name -> Statistic
	2,  // 2: Init.statistics_source:type_name -> Init.StatisticsSource
	1,  // 3: Init.predictive_type:type_name -> Init.PredictiveType
	8,  // 4: Init.buffer:type_name -> Buffer
	9,  // 5: Init.model:type_name -> Model
	3,  // 6: Init.acd_version:type_name -> Init.ACD
	22, // 7: Init.task_multiplier:type_name -> TaskMultiplier
	7,  // 8: PutTasks.tasks:type_name -> PutTask
	4,  // 9: RequestMessage.type:type_name -> RequestMessage.Type
	7,  // 10: RequestMessage.task:type_name -> PutTask
	10, // 11: RequestMessage.init:type_name -> Init
	11, // 12: RequestMessage.init_automatic:type_name -> InitAutomatic
	12, // 13: RequestMessage.statistic:type_name -> Statistic
	13, // 14: RequestMessage.errRate:type_name -> ErrRate
	22, // 15: RequestMessage.taskMultiplier:type_name -> TaskMultiplier
	14, // 16: RequestMessage.busyFactor:type_name -> BusyFactor
	16, // 17: RequestMessage.tasks:type_name -> PutTasks
	5,  // 18: TaskEvent.type:type_name -> TaskEvent.Type
	6,  // 19: ServiceMessage.type:type_name -> ServiceMessage.Type
	18, // 20: ServiceMessage.request:type_name -> GetTask
	19, // 21: ServiceMessage.init:type_name -> InitResponse
	20, // 22: ServiceMessage.event:type_name -> TaskEvent
	17, // 23: PDS.Start:input_type -> RequestMessage
	17, // 24: PDS.StartProgressive:input_type -> RequestMessage
	21, // 25: PDS.Start:output_type -> ServiceMessage
	21, // 26: PDS.StartProgressive:output_type -> ServiceMessage
	25, // [25:27] is the sub-list for method output_type
	23, // [23:25] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_pds_proto_init() }
func file_pds_proto_init() {
	if File_pds_proto != nil {
		return
	}
	file_pds_proto_msgTypes[3].OneofWrappers = []any{
		(*Init_RuleId)(nil),
		(*Init_RuleName)(nil),
		(*Init_ApplicationId)(nil),
		(*Init_ApplicationName)(nil),
	}
	file_pds_proto_msgTypes[4].OneofWrappers = []any{
		(*InitAutomatic_RuleId)(nil),
		(*InitAutomatic_RuleName)(nil),
		(*InitAutomatic_ApplicationId)(nil),
		(*InitAutomatic_ApplicationName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pds_proto_rawDesc), len(file_pds_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pds_proto_goTypes,
		DependencyIndexes: file_pds_proto_depIdxs,
		EnumInfos:         file_pds_proto_enumTypes,
		MessageInfos:      file_pds_proto_msgTypes,
	}.Build()
	File_pds_proto = out.File
	file_pds_proto_goTypes = nil
	file_pds_proto_depIdxs = nil
}
