// PDS gRPC contract for the Voximplant Predictive Dialer System.
// Clients open a bidirectional stream, send INIT, then respond to GET_TASK
// with PUT_TASK messages and observe TASK_EVENT updates.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: pds.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PDS_Start_FullMethodName            = "/PDS/Start"
	PDS_StartProgressive_FullMethodName = "/PDS/StartProgressive"
)

// PDSClient is the client API for PDS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PDS is the Predictive Dialer System service.
type PDSClient interface {
	// Start opens a predictive dialing session (bidirectional stream).
	Start(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestMessage, ServiceMessage], error)
	// StartProgressive opens a progressive dialing session (bidirectional stream).
	StartProgressive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestMessage, ServiceMessage], error)
}

type pDSClient struct {
	cc grpc.ClientConnInterface
}

func NewPDSClient(cc grpc.ClientConnInterface) PDSClient {
	return &pDSClient{cc}
}

func (c *pDSClient) Start(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestMessage, ServiceMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PDS_ServiceDesc.Streams[0], PDS_Start_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestMessage, ServiceMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PDS_StartClient = grpc.BidiStreamingClient[RequestMessage, ServiceMessage]

func (c *pDSClient) StartProgressive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestMessage, ServiceMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PDS_ServiceDesc.Streams[1], PDS_StartProgressive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestMessage, ServiceMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PDS_StartProgressiveClient = grpc.BidiStreamingClient[RequestMessage, ServiceMessage]

// PDSServer is the server API for PDS service.
// All implementations must embed UnimplementedPDSServer
// for forward compatibility.
//
// PDS is the Predictive Dialer System service.
type PDSServer interface {
	// Start opens a predictive dialing session (bidirectional stream).
	Start(grpc.BidiStreamingServer[RequestMessage, ServiceMessage]) error
	// StartProgressive opens a progressive dialing session (bidirectional stream).
	StartProgressive(grpc.BidiStreamingServer[RequestMessage, ServiceMessage]) error
	mustEmbedUnimplementedPDSServer()
}

// UnimplementedPDSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPDSServer struct{}

func (UnimplementedPDSServer) Start(grpc.BidiStreamingServer[RequestMessage, ServiceMessage]) error {
	return status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPDSServer) StartProgressive(grpc.BidiStreamingServer[RequestMessage, ServiceMessage]) error {
	return status.Error(codes.Unimplemented, "method StartProgressive not implemented")
}
func (UnimplementedPDSServer) mustEmbedUnimplementedPDSServer() {}
func (UnimplementedPDSServer) testEmbeddedByValue()             {}

// UnsafePDSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PDSServer will
// result in compilation errors.
type UnsafePDSServer interface {
	mustEmbedUnimplementedPDSServer()
}

func RegisterPDSServer(s grpc.ServiceRegistrar, srv PDSServer) {
	// If the following call panics, it indicates UnimplementedPDSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PDS_ServiceDesc, srv)
}

func _PDS_Start_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PDSServer).Start(&grpc.GenericServerStream[RequestMessage, ServiceMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PDS_StartServer = grpc.BidiStreamingServer[RequestMessage, ServiceMessage]

func _PDS_StartProgressive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PDSServer).StartProgressive(&grpc.GenericServerStream[RequestMessage, ServiceMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PDS_StartProgressiveServer = grpc.BidiStreamingServer[RequestMessage, ServiceMessage]

// PDS_ServiceDesc is the grpc.ServiceDesc for PDS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PDS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PDS",
	HandlerType: (*PDSServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Start",
			Handler:       _PDS_Start_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StartProgressive",
			Handler:       _PDS_StartProgressive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pds.proto",
}
